import Foundation
import SwiftData

/// Represents a physical document or receipt scanned from the user's photo library.
/// This model is persisted entirely offline using SwiftData.
@Model
final class IndexedPhoto {
    /// The exact underlying identifier from Apple's Photos framework.
    /// Used to fetch the actual high-res image or thumbnail on demand.
    @Attribute(.unique) var assetIdentifier: String
    
    /// Raw text strings extracted via the Vision OCR framework.
    var tags: [String]
    
    /// The semantic vector generated by Core ML.
    /// Used for cosine similarity search (e.g., matching "coffee" to an image of a mug).
    var embedding: [Float]?
    
    /// Initializes a new document record.
    /// - Parameters:
    ///   - assetIdentifier: The `localIdentifier` from the `PHAsset`.
    ///   - tags: An array of recognized text strings from the image.
    ///   - embedding: The multi-dimensional vector array (defaults to nil).
    init(assetIdentifier: String, tags: [String] = [], embedding: [Float]? = nil) {
        self.assetIdentifier = assetIdentifier
        self.tags = tags
        self.embedding = embedding
    }
}
